angular.module('raceday', [
  'lodash'
  'markdown'
  'moment'
  'raceday.activity'
  'raceday.animation'
  'raceday.events'
  'raceday.modelHelpers'
  'raceday.forms'
  'raceday.jsonHelpers'
  'raceday.stringHelpers'
  'raceday.metadata'
  'raceday.prompt'
  'raceday.search'
  'raceday.uiRouterAddons'
  'raceday.urlHelpers'
])
